Add basic react structure
blueberryapps/translation-server pull request #61
Opened 2017-03-23 12:17 UTC by ondrejbartas

2017-03-24 12:57 UTC, ondrejbartas commented on app/react/browser/.eslintrc
> +    "browser": true
realy? No eslint rules at all??

2017-03-24 12:58 UTC, ondrejbartas commented on app/react/browser/configureStoreWithHistory.js
> +    initialState:       window.__INITIAL_STATE__, // eslint-disable-line no-underscore-dangle
you are not passing INITIAL STATE from rails.

2017-03-24 12:58 UTC, ondrejbartas commented on app/react/browser/lib/listenWindowResize.react.js
> +
pls remove this.... Better to use `radium-flex`

2017-03-24 12:59 UTC, ondrejbartas commented on app/react/common/configureStore.js
> +  const initialStateWithPersistence = reviveStateFromPersistence(initialState, persistenceStore);
no need for this. You can get data directly from rails

2017-03-24 12:59 UTC, ondrejbartas commented on app/react/common/lib/Cookie.js
> +  }
no need for cookies

2017-03-24 12:59 UTC, ondrejbartas commented on app/react/common/lib/device/__test__/actions.spec.js
> +      payload: {
no need for this

2017-03-24 13:00 UTC, ondrejbartas commented on app/react/common/lib/device/__test__/reducer.spec.js
> +import test from 'ava';
what about jest?

2017-03-24 13:00 UTC, ondrejbartas commented on app/react/common/lib/persistence/__test__/actions.spec.js
> +  };
no need for persistance

2017-03-24 13:48 UTC, laxplaer commented
Hello @ondrejbartas,

long time no see. :) May I ask what is this about? :)

2017-03-27 12:30 UTC, kepi74 commented on .eslintrc
> +  "globals": {
simplify it with https://www.npmjs.com/package/eslint-plugin-jest
and use env to handle browser/node globals
```json
    "env": {
        "browser": true,
        "node": true,
        "jest/globals": true,
    }

2017-03-28 05:16 UTC, kepi74 commented on package.json
> +    "ava": "0.16.0",
Listed packages are `devDependencies` I think. And do we need `babelify`, `browserify`, `uglifyify` and `watchify` packages?

```diff 
 +    "ava": "0.16.0",
 +    "babel-loader": "^6.2.10",
 +    "babel-plugin-transform-runtime": "^6.15.0",
 +    "babel-polyfill": "^6.20.0",
 +    "babel-preset-es2015": "^6.18.0",
 +    "babelify": "^6.3.0",
 +    "browserify": "^12.0.1",
 +    "file-loader": "^0.10.1",
 +    "gulp": "^3.9.1",
 +    "gulp-babel": "^5.3.0",
 +    "gulp-eslint": "2.0.0",
 +    "gulp-rename": "^1.2.2",
 +    "gulp-swig": "^0.8.0",
 +    "gulp-uglify": "^1.5.1",
 +    "html-webpack-plugin": "^2.28.0",
 +    "jest-cli": "^19.0.2",
 +    "morgan": "^1.7.0",
 +    "react-addons-perf": "^15.4.2",
 +    "react-dev-utils": "^0.4.2",
 +    "react-hot-loader": "3.0.0-beta.6",
 +    "react-test-renderer": "^15.4.2",
 +    "source-map-support": "^0.4.9",
 +    "uglifyify": "^3.0.1",
 +    "url-loader": "^0.5.8",
 +    "watchify": "^3.7.0",
 +    "weakmap": "0.0.6",
 +    "webpack": "2.2.0",
 +    "webpack-dev-middleware": "^1.9.0",
 +    "webpack-hot-middleware": "^2.17.1",
 +    "webpack-isomorphic-tools": "^2.6.6"

2017-03-28 09:14 UTC, ondrejbartas commented on app/react/browser/createRoutes.js
> +import { IndexRoute, Route } from 'react-router';
what about using new router?

2017-03-28 09:16 UTC, ondrejbartas commented on app/views/react/index.html.slim
> +  | window.__INITIAL_STATE__ = '#{@initial_state}';
👍 but add new line 

set your editor to do it automatically

2017-03-28 09:17 UTC, ondrejbartas commented on package.json
> +  "ava": {
why do we need ava? Why not to have only jest?

2017-03-28 09:21 UTC, kepi74 commented on package.json
> +  "ava": {
Ava should be removed after rewriting tests to Jest. It will be better to do it new PR, I think.

2017-03-28 09:27 UTC, kepi74 commented on app/react/browser/createRoutes.js
> +import { IndexRoute, Route } from 'react-router';
⚠️ `react-router-redux` isn't compatible with latest `react-router@v4.0.0-beta`

2017-03-30 14:41 UTC, tomaass commented on app/react/common/configureStore.js
> +    init: railsState
@attilakiss323 so this helps because now it's object?

2017-04-07 10:20 UTC, ondrejbartas commented on app/react/browser/createRoutes.js
> +import { IndexRoute, Route } from 'react-router';
it is

2017-04-07 10:20 UTC, ondrejbartas commented on app/react/browser/createRoutes.js
> +import { IndexRoute, Route } from 'react-router';
check out haystack 🗡

2017-04-07 11:25 UTC, ondrejbartas commented
@attilakiss323 @kepi74 REBASED 💣

2017-04-07 12:16 UTC, kepi74 requested changes

2017-04-07 12:16 UTC, kepi74 commented on .babelrc
> +    "transform-class-properties",
`transform-class-properties` is part of `stage-2` preset.

2017-04-07 12:16 UTC, kepi74 commented on .eslintrc
> +    "window": false
`window` is covered by `env.browser = true`

2017-04-07 12:16 UTC, kepi74 commented on .eslintrc
> +  "globals": {
Remove globals covered by `env.jest = true`
https://github.com/facebook/jest/blob/master/packages/eslint-plugin-jest/src/index.js

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/app/Header.react.js
> +  () => ({}),
Just `null` works too.

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/app/__tests__/App.react.spec.js
> +import { shallow } from 'enzyme';
Mix of approaches. Snapshots should be created by Jest, not by enzyme.

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/app/menu/Menubar.react.js
> +    change('VerticalMenu', !isVerticalMenuShown);
Rename action `change`, pls. It's not clear what this action do.

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/components/Select.react.js
> +  renderOption(option) {
Extract to component, pls.

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/components/handleEvent.js
> +export default function (name, eventHandler, event) {
Wrong location of file. It's helper, not component.

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/createRoutes.js
> +import { IndexRoute, Route } from 'react-router';
It's not :). There are issues with redux actions and transitions are not working.
https://github.com/reactjs/react-router-redux

2017-04-07 12:16 UTC, kepi74 commented on app/react/browser/createRoutes.js
> +export default function createRoutes() {
Why? With readax-router-redux it's better to handle Google Analytics in middleware.

2017-04-11 08:42 UTC, merged